### ISSUE TITLE
bcrypt breaks continuous azure deployment

### ISSUE THREAD

**Issue by dduugg** [selfhub/selfhub#104]
More info [here](http://stackoverflow.com/questions/14573488/error-compiling-bcrypt-node-js). Looks like it can be solved by replacing either bcrypt or azure :stuck_out_tongue_winking_eye:

**Comment by ndraiman** [comment]
I just encountered this problem myself.

After searching for a solution for the past hour, the following worked flawlessly for me:
1. Goto your Web App console (found in the web app **Tools**)
2. type: `npm install bcrypt`

i received no output following the command, but going into the Web App node_modules folder i found bcrypt and all its dependencies there.

continuous deployment worked flawlessly ever since, hope this helps others!
